# 서버 설정
server:
  port: 8080  # 개발 환경의 기본 포트 번호

# H2 데이터베이스 설정 (메모리 모드 사용)
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1  # H2 메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver           # H2 JDBC 드라이버

  jpa:
    hibernate:
      ddl-auto: update                         # 스키마 자동 업데이트
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true                            # H2 콘솔 활성화 (개발 모드에서 사용)
      path: /h2-console

  data:
    # MongoDB 설정
    mongodb:
      uri: mongodb://localhost:27017/dev_database  # MongoDB 연결 URI (로컬 개발 환경)
      database: dev_database   # H2 콘솔 경로 설정
  # 국제화 설정
  messages:
    basename: messages
    encoding: UTF-8
  # 스프링 프로파일 설정
  profiles:
    active: dev

# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework: DEBUG
